Development
andela-aatanda/checkpoint3-document-management-api pull request #1
Opened 2017-01-13 14:31 UTC by andela-aatanda

## What does this PR do?
This PR implement README.md description

## How to test this manually?

Run in Postman

2017-01-15 05:43 UTC, andela-odaniel commented
*.travis.yml*
I think the database is provisioned just before the build. I doubt trying to drop if exist is essential

*document.spec.js*
variable name `fakeAdminToken` should probably be renamed. If you want to create another token you know to not work to test that a user can't use an expired or non-existent token, what do you call it?
Line 43. you can just test if res.body.createdAt is defined
Line 48 misleading test title, you should probably correct that
Line 53 status code 400 means bad request. The test is unclear is you mean it can't be found it should be 404
Line 78, 87 test title should read 'for unauthorized requests'
Line 91 Missing authorization. status code should be 401
Line 116: Test title is ambiguous specify action being carried out
Line 125: Test is actually for updating functionality, title should be more reflective of this
Line 135: see line 116 comment.
Line 144,154: Reformat test title e.g 'should be able to delete document', 'unauthorized user should be unable to delete document'

*role.spec.js*
Line 34, 44 Essentially the same test. roll together
Line 49 More specific status code is 403. consider.
Line 91, 100: Essentially Duplicate test
Line 87: Request is actually well phrase. 422 is a more appropriate status code. The reason can be given in the response

*user.spec.js*
Line 62: Misleading response. no credentials were provided
Line 113: Incorrect status code. 202 is intended for asynchronous or batch operations where the final response is returned later. Consider using 204 (accepted with No Content response) or 200 (Generic success to which a response can be appended)
Line 148, 158: Duplicate test
Line 151,161: Conventionally a 404 response is used to mask the existence of the endpoint but it's such an obvious endpoint that this is probably not worth it. This is just my opinion
Line 176, 186: Duplicate test
Line 190: Wrong status code. 302 means redirect. See Line 113 comment for more info.

*config.json*
 This file contains secrets that should be protected. Consider using env variables

*controller/users.js*
Line 6: You've hardcoded the secret here.
Line 94: Consider moving the authentication functionality to the model
Line 156. I'm not sure what the 302 status code does. incorrect perhaps?

*models/document.js*
Line 17: Thanks. I learned about the isIn validate option. :+1: 

*models/user.js*
Line 25: RoleId field is redundant. The model association to Role defined below creates this field.
Line 53: You don't check if there's been a change to the password before hashing it again. This way you will rehash an already hashed password. 

*routes/index.js*
Line 1-3: inconsistent naming scheme

*app.js*
Line 25: exports the app object. Consider splitting into server.js(creates and exports ap) and index.js(imports app and starts the server).

`<GENERAL RANT>`
  A test name is a contract. A test should fulfill that contract by doing exactly what the test says it does. The reason for this is that other developers will probably not look closely at your test trusting it to do what it has said. A breach of this contract has security and maintainability implications.

Consider not using classes in some cases. exporting object and functions allows for increased flexibility and more efficient memory usage. Classes add visible structure but this app isn't large enough to need it.

Consider ways to structure your code to reduce branches. Branches increase the [Cyclomatic Complexity](https://en.wikipedia.org/wiki/Cyclomatic_complexity) of your code making testing more difficult. 

:smile: 
`</GENERAL RANT>`

2017-01-16 08:01 UTC, michael-alade requested changes

2017-01-16 08:01 UTC, michael-alade commented on server/controllers/user.js
> +        return res.status(302).send({ message: 'User already exists' });
This status code should be `409`

2017-01-16 08:01 UTC, michael-alade commented on server/controllers/user.js
> +            res.status(404).send({ message: 'Username or password incorrect' });
This should be `400` due to client error. `404` is used when a resource is not found

2017-01-19 14:46 UTC, merged